<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://servlet.schemastore.mitre.org" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://servlet.schemastore.mitre.org" xmlns:intf="http://servlet.schemastore.mitre.org" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://servlet.schemastore.mitre.org" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getInteger">
    <complexType/>
   </element>
   <element name="getIntegerResponse">
    <complexType>
     <sequence>
      <element name="getIntegerReturn" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getIntegerRequest">

      <wsdl:part element="impl:getInteger" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="getIntegerResponse">

      <wsdl:part element="impl:getIntegerResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:portType name="Temp">

      <wsdl:operation name="getInteger">

         <wsdl:input message="impl:getIntegerRequest" name="getIntegerRequest"/>

         <wsdl:output message="impl:getIntegerResponse" name="getIntegerResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TempSoapBinding" type="impl:Temp">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getInteger">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getIntegerRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getIntegerResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TempService">

      <wsdl:port binding="impl:TempSoapBinding" name="Temp">

         <wsdlsoap:address location="http://localhost:8080/SchemaStore/services/Temp"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
